trigger:
  batch: true
  branches:
    include:
      - main

parameters:
  - name: project
    displayName: Project to Deploy
    type: string
    values:
      - FunctionAppWithCosmosDb
      - FunctionAppWithSql
      - FunctionAppWithTableStorage

variables:
  serviceConnection: PersonalSubscriptionServiceConnection

stages:
  - template: templates/stages/build.yml@Self
    parameters:
      stage: Build

  - template: templates/stages/deploy.yml@Self
    parameters:
      stage: Deploy
      dependsOn:
        - Build
      serviceConnection: ${{ variables.serviceConnection }}
      project: ${{ parameters.project }}
